name: lixshop
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_svg:
  velocity_x:
  image_picker:
  google_nav_bar:
  line_icons:
  carousel_slider:
  dots_indicator:
  google_fonts:
  shared_preferences:
  get:
  popup_menu:
  path_provider:
  url_strategy:
  expand_widget:
  dropdown_button2:
  expandable:
  readmore:
  flutter_dotenv:
  dio:
  flutter_bloc: ^8.0.1
  animations:
  flutter_staggered_grid_view:
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  flutter_html:
  page_indicator:
  shimmer:
  device_preview:
  intl: ^0.17.0
  smooth_page_indicator: ^1.0.0+2
  hexcolor: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3
  flutter_app_name: ^0.1.1
  rename: any
  permission_handler: ^9.2.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/logos/ic_launcher_android.png"
  image_path_ios: "assets/logos/ic_launcher_ios.png"
flutter_app_name:
  name: "LixShop"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/logos/
    - assets/json/
    - assets/icons/
    - .env
    - assets/get_started/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
