List restaurants = [
  {
    "img": "assets/images/lix1.png",
    "title": "Bột giặt LixBột giặt LixBột giặt LixBột t",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Bột giặt",
  },
  {
    "img": "assets/images/lix2.jpg",
    "title": "Nước giặt",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Nước giặt",
  },
  {
    "img": "assets/images/lix3.png",
    "title": "Dầu rửa chén",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Dầu rửa chén",
  },
  {
    "img": "assets/images/lix4.jpg",
    "title": "Iron & Stone",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Iron & Stone",
  },
  {
    "img": "assets/images/lix1.png",
    "title": "Bột giặt Lix",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Bột giặt",
  },
  {
    "img": "assets/images/lix2.jpg",
    "title": "Nước giặt",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Nước giặt",
  },
  {
    "img": "assets/images/lix3.png",
    "title": "Dầu rửa chén",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Dầu rửa chén",
  },
  {
    "img": "assets/images/lix4.jpg",
    "title": "Iron & Stone",
    "address": "12345VNĐ",
    "rating": "4.5",
    "type": "Iron & Stone",
  },
];
